### PR TITLE
use asset role instead of asset name to define which asset is the labels

### PR DESCRIPTION
**Pull request by philvarner**

### CODE REVIEW

**Review by jisantuc — APPROVED** [review]
👍🏻 thanks for re-targeting to the new repo

**Comment by philvarner** [comment]
I don't have permission to merge this, even through it's approved

**Comment by jisantuc** [comment]
Woops lemme see if I can sort that out

**Comment by jisantuc** [comment]
I think you should be able to merge once you accept the organization invite. If that's still not true for some reason, I'll merge it and try to figure out what we did to offend GitHub.

**Comment by philvarner** [comment]
I hadn't seen the invite yet -- accepting it worked

**Comment by jisantuc** [comment]
Np I just wanted the note about it to be here as well in case you weren't looking at gitter

**Pull request merged**
